language: java
jdk: oraclejdk8

# install Neo4j manually because Neo4j as a service doesn't work
before_install:
  - wget dist.neo4j.org/neo4j-community-3.0.6-unix.tar.gz
  - tar -xzf neo4j-community-3.0.6-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-3.0.6/conf/neo4j-server.properties
  - neo4j-community-3.0.6/bin/neo4j start
  
services:
    - postgresql
    - cassandra

before_script: 
    - createdb test
    - createuser test -d -s
    - |- 
        cqlsh -e "create keyspace test with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
    - cd ground-core/scripts/postgres && python2.7 postgres_setup.py test test && cd ../../..
    - cd ground-core/scripts/cassandra && python2.7 cassandra_setup.py test && cd ../../..

script: mvn clean test

after_success: 
  - mvn clean test jacoco:report coveralls:report
  
