language: java
jdk: oraclejdk8
sudo: required

before_script:
  - sh -e ci/install.sh
  - sh -e ci/init.sh 

script:
  - mvn clean test

after_success:
  - sh -e ci/server.sh
  - mvn clean test jacoco:report coveralls:report
