language: java
jdk: oraclejdk8
sudo: required

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/pip

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates.
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - sh -e resources/ci/install.sh
  - chmod a+x ./client/java/gradlew

before_script:
  - sh -e resources/ci/init.sh
  - chmod +x sbt-dist/bin/sbt

install:
  - pip install -r client/python/requirements.txt

script:
  - ./sbt-dist/bin/sbt test
  - client/python/nosetests

after_success:
  - ./sbt-dist/bin/sbt jacoco:cover
  - bash <(curl -s https://codecov.io/bash)
