language: java
jdk: oraclejdk8
script: mvn clean test

services:
    - postgresql
    - cassandra

before_script: 
    - createdb test
    - createuser test -d -s
    - |- 
        cqlsh -e "create keyspace test with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
