language: java
jdk: oraclejdk8

services:
    - postgresql
    - cassandra

before_script: 
    - createdb test
    - createuser test -d -s
    - cqlsh -e "SHOW VERSION;"
    - |- 
        cqlsh -e "create keyspace test with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
    - cd scripts/postgres && python2.7 postgres_setup.py test test && cd ../..
    - cd scripts/cassandra && python2.7 cassandra_setup.py test && cd ../..

script: mvn clean test
