language: java
jdk: oraclejdk8
sudo: required

env:
  - NEO4J_VERSION=3.1.2

before_script:
  - sh -e resources/ci/install.sh
  - sh -e resources/ci/init.sh

script:
  - sbt test

after_success:
  - sbt jacoco:cover
  - bash <(curl -s https://codecov.io/bash)
  - sh -e ci/server.sh
