language: java
jdk: oraclejdk8
sudo: required

before_script:
  - sh -e resources/ci/install.sh
  - sh -e resources/ci/init.sh

script:
  - sbt test

after_success:
  - sbt jacoco:cover
  - bash <(curl -s https://codecov.io/bash)
