language: java
jdk: oraclejdk8
sudo: required

before_script:
  - sh -e resources/ci/install.sh
  - sh -e resources/ci/init.sh
  - chmod +x sbt-dist/bin/sbt

script:
  - ./sbt-dist/bin/sbt test

after_success:
  - ./sbt-dist/bin/sbt jacoco:cover
  - bash <(curl -s https://codecov.io/bash)
