language: java
jdk: oraclejdk8

sudo: required

addons:  
  apt:
    packages:
      - oracle-java8-installer

before_install:  
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz && tar -xvzf apache-cassandra-3.7-bin.tar.gz
  - sudo sh ./apache-cassandra-3.7/bin/cassandra -R >> /dev/null
  - sleep 60

services:
    - postgresql
    - neo4j

before_script:
    - createdb test
    - createuser test -d -s
    - cqlsh -e "SHOW VERSION;"
    - |-
        cqlsh -e "create keyspace test with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
    - cd ground-core/scripts/postgres && python2.7 postgres_setup.py test test && cd ../../..
    - cd ground-core/scripts/cassandra && python2.7 cassandra_setup.py test && cd ../../..

script: mvn clean test

after_success:
    - mvn clean test jacoco:report coveralls:report
  
