language: 
  - java
  - python  # For Python client library
jdk: 
  - oraclejdk8
  - oraclejdk7
python:     # For Python client library
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: required

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/pip

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates.
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_install:
  - sh -e resources/ci/install.sh

install: "pip install -r requirements.txt" # For Python client library

before_script:
  - sh -e resources/ci/init.sh
  - chmod +x sbt-dist/bin/sbt

script:
  - ./sbt-dist/bin/sbt test
  - client/python/nosetests # For Python client library
  # - mvn client/java/test # For Java client library

after_success:
  - ./sbt-dist/bin/sbt jacoco:cover
  - bash <(curl -s https://codecov.io/bash)